data ={
'legit': 'ENGLISH BABYSITTING JOBS IN PARIS - BE MY NOUNOU',
'legit': 'Babysitting Jobs in English with Speaking-Agency',
'legit': 'Babysitting Jobs in English with Speaking-Agency',
'suspicious':'Parisk: sneaking for an upskirt',
'legit': 'CHERCHE H/F pour ménage ( 0756950829)',
'legit': 'ENGLISH TEACHING JOBS WITH SPEAKING-AGENCY',
'legit': 'BABYSITTING and TUTORING JOB with Be My Nounou',
'suspicious':'part time Job in paris for ukrainien and russian speaker',
'legit':'Speaking-Agency wants YOU',
'legit':'Recruiting English speaking babysitter 15 EUR/hour',
'legit':'US/UK afterschool babysitter Paris 3 Thursday Only (Paris)',
'legit':'CHILDCARE JOBS FOR ENGLISH SPEAKERS',
'suspicious':'English Native Speaker Needed for Conversations',
'suspicious':'Parisk! Sneaking for an upskirt',
'suspicious':'Photographer In Paris for Tourists, Lifestyle and Portraits',
'legit':'collecteur de loyer',
'legit':'Housekeeper Needed 2h a Week',
'legit':'English mother tongue student',
'legit':'collecteur de loyer',
'suspicious':'FUN+SPICE agency looking for the right lady',
'suspicious':'female model wanted',
'suspicious':'Summoning of the Muse',
'suspicious':'VIP PLACE/ LOOKING FOR PRETTY GIRL$$',
'suspicious':'part time job with accommodation',
'suspicious':'for polish girls, stay for free in paris',
'suspicious':'part time Job in paris for ukrainien and russian speaker',
'legit': 'Child care in Pantin (Metro ligne 5 Église de Pantin)',
'legit': 'If you do one thing this weekend - check out Speaking-Agency',
'legit': 'CHILDCARE JOBS FOR ENGLISH SPEAKERS',
'suspicious':'part time Job in paris for ukrainien and russian speaker',
'suspicious':'part time job with accommodation',
'legit': 'ENGLISH JOBS IN PARIS - BE MY NOUNOU',
'legit':'Looking for english teacher',
'legit': 'ENGLISH TEACHING JOBS WITH SPEAKING-AGENCY',
'legit':'production/videography internship',
'legit': 'Babysitting Jobs in English with Speaking-Agency',
'legit': 'Nannying in English with Speaking-Agency',
'legit': 'CHILDCARE JOBS FOR ENGLISH SPEAKERS',
'suspicious':'job part time',
'suspicious':'Modele pour Tournage X',
'suspicious':'Modele Homme 25 et 35 ans pour Video X privé',
'suspicious':'Modele Homme 25 et 35 ans pour Video X privé',
'legit': 'Tutor English in France with Speaking-Agency',
'legit': 'Punctual missions for agency Myluxshop' ,
'suspicious':'Salary 300-800€ for 1 mission',
'legit': 'Babysitting Jobs in English with Speaking-Agency',
'legit': 'After school native English babysitter',
'legit': 'CHILDCARE JOBS FOR ENGLISH SPEAKERS',
'legit': 'Afterschool babysitter needed - Urgent',
'suspicious': 'Personal Shopper Needed!',
'suspicious':'Special event',
'suspicious': 'event for 3 days',
'suspicious':'Besoin de quelqu un avec un compte Neteller et Skype',
'legit':  "Looking for models Foot models needed",
'legit': 'ENGLISH TEACHING JOBS WITH SPEAKING-AGENCY',
'legit': 'ENGLISH BABYSITTING JOBS IN PARIS - BE MY NOUNOU',
'legit': 'Become a Babysitter with Speaking-Agency',
'suspicious': 'Personal Shopping',
"legit": 'Book Translation',
'legit': 'Photographer In Paris for Tourists',
'legit':'Lifestyle and Portraits',
'suspicious':'Artistic modeling for portfolio',
'legit':'Au Pair Jobs in Paris with Speaking-Agency',
'suspicious':'Female Models Required',
'legit':'Nannying in English with Speaking-Agency',
'suspicious':'Personal Shopping',
'legit':'Babysitting Jobs in English with Speaking-Agency',
'legit':'Bilingual nursery | English speaking child care position CDI',
'legit':'Babysitting Jobs in English with Speaking-Agency',
'suspicious':'Personal Shopping',
'legit':'Babysitting Jobs in English with Speaking-Agency',
'legit':'Recruiting English speaking babysitter 15 EUR/hour',
'suspicious':'Personal Shopping Paris',
'suspicious':'a movie on real erotic stories',
'legit':'Driver camion utilitaire événement',
'legit':'EMT housemaid/babysitter',
'legit':'Free Internship for Upcoming Fashion Media',
'legit':'Internship for up and coming alternative fashion magazine',
'suspicious':'Parisk: Sneaking for an upskirt',
'legit':'Recherche de toute urgence un chauffeur particulier H/F',
'suspicious':'The lady and The Smoke photocontest',
'suspicious':'Need someone to buy things (chocolate) and ship to United States',
'suspicious':'Voyeur looking for straight couple',
'suspicious':'Personal Shopping',
'legit':'Seeking Python Master'
}
